import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Manual sidebar — doc IDs are the file path under docs/ minus the extension.
// Kept explicit (not autogenerated) so the reading order is curated, not
// alphabetical.
const sidebars: SidebarsConfig = {
  docs: [
    'getting-started',
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/events',
        'concepts/interceptors',
        'concepts/reducer',
        'concepts/sessions',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [
        'recipes/quickstart-offline',
        'recipes/connect-http-backend',
        'recipes/connect-agno',
        'recipes/connect-langgraph',
        'recipes/connect-copilotkit-runtime',
        'recipes/retry-and-auth',
        'recipes/logging-and-tracing',
        'recipes/pii-redaction-sentry',
        'recipes/cancel-a-run',
        'recipes/persist-sessions',
        'recipes/secure-sessions',
        'recipes/interrupt-resume',
        'recipes/generative-ui',
        'recipes/theming',
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      items: ['patterns/stream-cancellation'],
    },
    'api-reference',
    'migration-guide',
    'adapter-cookbook',
  ],
};

export default sidebars;
